# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiUIhi6VmbY_6mYPjpGL7dzk5C5s63YX
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# -----------------------------------------------------------------
# KONFIGURASI HALAMAN
# -----------------------------------------------------------------
st.set_page_config(
    page_title="FashionTrendChecker (Explained)",
    page_icon="👕",
    layout="wide"
)

# -----------------------------------------------------------------
# FUNGSI BANTUAN
# -----------------------------------------------------------------
def format_bulan_indo(date_obj):
    """Mengubah datetime menjadi string bulan Indonesia (Contoh: Februari 2025)"""
    bulan_map = {
        1: 'Januari', 2: 'Februari', 3: 'Maret', 4: 'April', 5: 'Mei', 6: 'Juni',
        7: 'Juli', 8: 'Agustus', 9: 'September', 10: 'Oktober', 11: 'November', 12: 'Desember'
    }
    return f"{bulan_map[date_obj.month]} {date_obj.year}"

def get_production_recommendation(predicted_demand, safety_stock_pct):
    safety_stock_units = predicted_demand * (safety_stock_pct / 100)
    recommended_quantity = predicted_demand + safety_stock_units
    return int(recommended_quantity), int(safety_stock_units)


# -----------------------------------------------------------------
# --- LOAD DATA DARI CSV ---
# -----------------------------------------------------------------
@st.cache_data
def load_and_train_model():
    try:
        # MEMBACA FILE CSV EKSTERNAL
        df = pd.read_csv("data_sample.csv")

        # Konversi format data agar aman
        df['Month'] = pd.to_datetime(df['Month'])
        df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')
        df['TrendScore'] = pd.to_numeric(df['TrendScore'], errors='coerce')
        df['USD_IDR'] = pd.to_numeric(df['USD_IDR'], errors='coerce')
        df = df.dropna()

        # Filter: Hapus data tahun 2020 (MonthIndex < 13) karena anomali pandemi
        df = df[df['MonthIndex'] >= 13]

        # --- LATIH MODEL UTAMA ---
        features = ['MonthIndex', 'TrendScore', 'USD_IDR']
        target = 'Sales'

        X_train = df[features]
        y_train = df[target]

        model = LinearRegression()
        model.fit(X_train, y_train)

        return model, df, features, target

    except FileNotFoundError:
        st.error("ERROR: File 'data_sample.csv' tidak ditemukan. Pastikan file ada di folder yang sama.")
        return None, None, None, None
    except Exception as e:
        st.error(f"Terjadi kesalahan saat membaca data: {e}")
        return None, None, None, None

# Eksekusi Load Data
model, df_history, features, target = load_and_train_model()

if model is None:
    st.stop()

# -----------------------------------------------------------------
# PROSES OTOMATISASI (Menentukan Bulan Berikutnya)
# -----------------------------------------------------------------
last_row = df_history.iloc[-1]
next_date = last_row['Month'] + pd.DateOffset(months=1)
next_month_text = format_bulan_indo(next_date)
next_month_index = int(last_row['MonthIndex']) + 1
next_trend_score = float(last_row['TrendScore'])
next_usd_idr = float(last_row['USD_IDR'])

# -----------------------------------------------------------------
# UI - SIDEBAR
# -----------------------------------------------------------------
st.sidebar.header("Parameter Produksi")
safety_stock_percent = st.sidebar.slider(
    "Persentase Safety Stock (%)",
    min_value=0, max_value=50, value=20,
    help="Cadangan produksi untuk menghindari kehabisan stok."
)

st.sidebar.markdown("---")
st.sidebar.subheader("Parameter Otomatis (Terdeteksi)")
st.sidebar.info(f"Data terakhir: **{format_bulan_indo(last_row['Month'])}**")
st.sidebar.text_input("Target Bulan (Index):", value=str(next_month_index), disabled=True)
st.sidebar.text_input("Trend Score (Terakhir):", value=str(next_trend_score), disabled=True)
st.sidebar.text_input("Kurs USD/IDR (Terakhir):", value=str(int(next_usd_idr)), disabled=True)


# -----------------------------------------------------------------
# UI - HALAMAN UTAMA
# -----------------------------------------------------------------
st.title("👕 FashionTrendChecker (Smart Forecast)")
st.subheader(f"Prediksi Permintaan: {next_month_text}")
st.markdown("---")

# -----------------------------------------------------------------
# --- HITUNG PREDIKSI ---
# -----------------------------------------------------------------
input_features = pd.DataFrame({
    'MonthIndex': [next_month_index],
    'TrendScore': [next_trend_score],
    'USD_IDR': [next_usd_idr]
})

pred_demand = int(model.predict(input_features)[0])
reco_prod, safety_units = get_production_recommendation(pred_demand, safety_stock_percent)

# -----------------------------------------------------------------
# --- OUTPUT UTAMA ---
# -----------------------------------------------------------------
col1, col2 = st.columns(2)
with col1:
    st.metric(
        label=f"Prediksi Permintaan ({next_month_text})",
        value=f"{pred_demand} unit"
    )
    st.caption("Prediksi AI berdasarkan pola 2021-2025.")

with col2:
    st.metric(
        label="✅ REKOMENDASI PRODUKSI",
        value=f"{reco_prod} unit",
        delta=f"+{safety_units} unit (Safety Stock)"
    )

st.markdown("---")

# -----------------------------------------------------------------
# --- VISUALISASI ---
# -----------------------------------------------------------------
st.subheader(f"Visualisasi Target: {next_month_text}")

avg_sales = df_history['Sales'].mean()
max_gauge = max(avg_sales * 2.0, reco_prod * 1.5)

fig_gauge = go.Figure(go.Indicator(
    mode = "gauge+number+delta",
    value = reco_prod,
    title = {'text': "Total Produksi (Unit)"},
    delta = {'reference': pred_demand},
    gauge = {
        'axis': {'range': [0, max_gauge]},
        'bar': {'color': "#2E8B57"},
        'steps' : [
            {'range': [0, pred_demand], 'color': "rgba(200, 200, 200, 0.3)"},
            {'range': [pred_demand, reco_prod], 'color': "rgba(255, 165, 0, 0.5)"},
            # --- PENAMBAHAN ZONA MERAH ---
            {'range': [reco_prod, max_gauge], 'color': "rgba(255, 0, 0, 0.4)"}
        ],
        'threshold' : {'line': {'color': "red", 'width': 4}, 'thickness': 0.75, 'value': pred_demand}
    }
))
st.plotly_chart(fig_gauge, use_container_width=True)

# -----------------------------------------------------------------
# --- INDIKATOR STATUS (BARU) ---
# -----------------------------------------------------------------
col_stat1, col_stat2, col_stat3 = st.columns(3)

with col_stat1:
    st.metric("Prediksi Permintaan", f"{pred_demand} Unit")

with col_stat2:
    st.metric("Target Produksi", f"{reco_prod} Unit")

with col_stat3:
    st.markdown("**Status Inventory:**")
    # Logika Status berdasarkan Safety Stock
    if safety_stock_percent <= 25:
        st.success("✅ **Aman (Optimal)**")
    elif safety_stock_percent <= 40:
        st.warning("⚠️ **Waspada (Stok Tebal)**")
    else:
        st.error("🛑 **Risiko Overproduction**")

st.markdown("<br>", unsafe_allow_html=True) # Spasi

# --- PENJELASAN VISUALISASI ---
st.info("""
**Cara Membaca Grafik Target:**
* **Jarum / Angka Utama:** Total unit yang **harus diproduksi** (Rekomendasi Akhir).
* **Garis Merah Kecil:** Angka **prediksi murni** (berapa banyak yang diprediksi akan laku).
* **Area Abu-abu:** Zona permintaan pasar (jumlah yang kemungkinan besar terjual habis).
* **Area Oranye:** Zona **Safety Stock** (cadangan aman agar tidak kehabisan stok jika permintaan melonjak).
* **Area Merah:** Zona **Risiko Overproduction** (Sebaiknya jangan produksi melebihi batas ini).
""")

# -----------------------------------------------------------------
# --- GRAFIK TREN ---
# -----------------------------------------------------------------
st.subheader("Tren Historis (Data Filtered)")

fig_history = go.Figure()

fig_history.add_trace(go.Scatter(
    x=df_history['Month'],
    y=df_history['Sales'],
    mode='lines+markers',
    name='Penjualan',
    line=dict(color='#1f77b4', width=3)
))

fig_history.add_trace(go.Scatter(
    x=df_history['Month'],
    y=df_history['TrendScore'],
    mode='lines',
    name='Skor Tren',
    yaxis='y2',
    line=dict(color='#ff7f0e', dash='dot')
))

fig_history.update_layout(
    xaxis_title='Bulan',
    yaxis=dict(title='Penjualan'),
    yaxis2=dict(title='Skor Tren', overlaying='y', side='right'),
    legend=dict(x=0, y=1.1, orientation='h'),
    hovermode="x unified"
)

st.plotly_chart(fig_history, use_container_width=True)

# -----------------------------------------------------------------
# --- TABEL DATA ---
# -----------------------------------------------------------------
with st.expander("Lihat Data CSV (Mulai Jan 2021)"):
    df_display = df_history.copy()
    df_display['Month'] = df_display['Month'].apply(lambda x: format_bulan_indo(x))
    st.dataframe(df_display, use_container_width=True)

# -----------------------------------------------------------------
# --- EVALUASI MODEL ---
# -----------------------------------------------------------------
st.markdown("---")
st.header("🔬 Evaluasi Performa Model")

# 1. Persiapkan Data
X = df_history[features]
y = df_history[target]

# 2. Split Data
X_train_eval, X_test_eval, y_train_eval, y_test_eval = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. Latih Model Evaluasi
model_eval = LinearRegression()
model_eval.fit(X_train_eval, y_train_eval)

# 4. Prediksi
y_pred_eval = model_eval.predict(X_test_eval)

# 5. Hitung Metrik
mae = mean_absolute_error(y_test_eval, y_pred_eval)
rmse = np.sqrt(mean_squared_error(y_test_eval, y_pred_eval))
r2 = r2_score(y_test_eval, y_pred_eval)

# 6. Tampilkan Metrik
col_eval1, col_eval2, col_eval3 = st.columns(3)
col_eval1.metric("MAE (Rata-rata Error)", f"{mae:.2f}")
col_eval2.metric("RMSE", f"{rmse:.2f}")
col_eval3.metric("R² Score (Akurasi)", f"{r2:.4f}")

# 7. Visualisasi Actual vs Predicted
st.subheader("Grafik Prediksi vs Aktual (Data Test)")

fig_eval = go.Figure()

fig_eval.add_trace(go.Scatter(
    x=y_test_eval,
    y=y_pred_eval,
    mode='markers',
    name='Data Test',
    marker=dict(color='blue', size=10, opacity=0.7)
))

min_val = min(y_test_eval.min(), y_pred_eval.min())
max_val = max(y_test_eval.max(), y_pred_eval.max())

fig_eval.add_trace(go.Scatter(
    x=[min_val, max_val],
    y=[min_val, max_val],
    mode='lines',
    name='Garis Ideal',
    line=dict(color='red', dash='dash')
))

fig_eval.update_layout(
    xaxis_title="Penjualan Aktual",
    yaxis_title="Penjualan Prediksi",
    title=f"Akurasi Model (R² = {r2:.2f})",
    showlegend=True
)

st.plotly_chart(fig_eval, use_container_width=True)

# --- PENJELASAN EVALUASI ---
st.info("""
**Penjelasan Metrik Evaluasi:**
* **MAE (Mean Absolute Error):** Rata-rata kesalahan prediksi dalam unit (misal: meleset ±50 baju). Semakin kecil semakin baik.
* **RMSE (Root Mean Squared Error):** Mirip MAE, tapi lebih sensitif jika ada kesalahan tebak yang sangat fatal.
* **R² Score:** Skor kepintaran model (0.0 sampai 1.0). Nilai di atas 0.7 artinya model sudah cukup pintar memahami pola pasar.

**Cara Membaca Grafik Scatter:**
* **Sumbu X:** Kenyataan (Berapa yang laku).
* **Sumbu Y:** Tebakan Model.
* **Garis Merah Putus-putus:** Target Sempurna.
* **Analisis:** Jika titik-titik biru menempel dekat dengan garis merah, berarti prediksi model sangat akurat. Jika menyebar jauh, berarti model masih sering salah tebak.
""")